### ISSUE TITLE
Contribute section needs an update

### ISSUE THREAD

**Issue by glvjr** [processing/processing-website#442] opened 2023-02-15 02:02 UTC
This is currently on the website in the Contribute section:

To contribute to Processing development, please visit Processing on GitHub to read instructions for downloading the code,[ building from the source](https://github.com/processing/processing/wiki/Build-Instructions), [reporting and tracking bugs](https://github.com/processing/processing/wiki/Report-Bugs), reporting and tracking bugs [creating libraries and tools](https://github.com/processing/processing/wiki).

"visit Processing on GitHub to read instructions for downloading the code"
- I do not see instructions on GitHub for downloading code

"[reporting and tracking bugs](https://github.com/processing/processing/wiki/Report-Bugs), reporting and tracking bugs"
- Duplicates and missing a comma at the end

"[building from the source](https://github.com/processing/processing/wiki/Build-Instructions),"
- This is directed to the Processing 3 instructions.
- There are now Processing 4 instructions:
[How to Build Processing](https://github.com/processing/processing4/blob/main/build/README.mdl)

"[creating libraries and tools](https://github.com/processing/processing/wiki)."

- This is directed to the Processing 3 _FAQ and Technical Information_ (Wiki)
- There is now a Processing 4 Wiki:
https://github.com/processing/processing4/wiki

Consider a bulleted list for the above instead of links in a paragraph.

**Comment by SableRaf** [comment] 2023-02-16 16:26
Hi @glvjr and thanks for your detailed report. If anyone wants to make a PR for these improvements I will happily merge it.

**Comment by Dev-Code24** [comment] 2023-02-18 18:20
let me do it. It is just a few minutes of work.

**Comment by Dev-Code24** [comment] 2023-02-18 18:38
The part where,
 
"visit Processing on GitHub to read instructions for downloading the code"

I do not see instructions on GitHub for downloading code

This part of the issue is to fixed in the github  [repo](https://github.com/processing/processing4) 
I have fixed other links.

**Comment by SableRaf** [comment] 2023-02-20 15:18
Fixed in https://github.com/processing/processing-website/commit/5d533529ea97df48fc47e16ad80e4720e8de6d14

**Closed by SableRaf** 2023-02-20 15:18 UTC
Labels: Help Wanted
