### ISSUE TITLE
noiseSeed() wrong seed value type

### ISSUE THREAD

**Issue by johhnry** [processing/processing-website#414] opened 2023-01-15 17:27 UTC
Hi,

I just found that the documentation for the [`noiseSeed(seed)`](https://processing.org/reference/noiseSeed_.html) function tells that it accepts an `int` value which is not correct since it accepts a `long` primitive data type:

https://github.com/processing/processing4/blob/main/core/src/processing/core/PApplet.java#L5077

Is this intentional? This might be confusing because I get an error in the Processing IDE about a type mismatch.

Thanks!

**Comment by SableRaf** [comment] 2023-01-20 18:51
Hi @johhnry and thanks for sharing this issue! Would you be able to share a minimal example showing this type mismatch error? I was unable to reproduce it.

**Comment by johhnry** [comment] 2023-01-21 12:04
Hi @SableRaf,

Thanks for the follow up, this is a bit weird since it works when passing an `int` but not a `float`:

```processing
float seed = 0;
noiseSeed(seed);

// -> The method noiseSeed(long) in the type PApplet is not applicable for the arguments (float)
```

I suppose that Java can implicitly convert between `int` to `long` but not `float` to `long`.

**Comment by SableRaf** [comment] 2023-01-25 09:25
Hi @johhnry. I investigated this further and the parameters should be handled automatically by the script that generates the reference ([this function](https://github.com/processing/processing-doclet/blob/9f5028c3bc46d128033527ca2b1d3b88d59b03d3/ReferenceGenerator/src/writers/BaseWriter.java#L363) specifically).

Please note that we are having an issue right now where [the Doclet script needs to be updated](https://github.com/processing/processing-doclet/issues/1) (help needed) before we can update the reference. Once the script is fixed, we can look at this issue again as it may be a holdover from the old reference.

**Comment by johhnry** [comment] 2023-01-25 16:15
Hi @SableRaf, thank you for investigating and linking this issue. I'll look at that repo if I have time ;)

**Comment by REAS** [comment] 2023-01-26 17:43
@benfry please check this, where do you think the issue lies?

**Comment by benfry** [comment] 2023-01-26 18:48
This applies to both `noiseSeed()` and `randomSeed()`. Both in fact take a `long` as an argument, though an `int` will work fine as well. We don't use `long` in any other API, so I suspect that the reference may have just been written to say `int` for clarity. 

Further, passing an `int` won't show an error, because an `int` can safely be upgraded to a `long` without any loss of data (as opposed to `float` to `int` or `long`). I think it probably falls in the range of an acceptable white lie… if someone knows what a `long` is, then they can pass it, but the vast majority of our users can safely use it with an `int`, and it would probably be more confusing to write an example that used `long` just for the formality of it.

**Comment by SableRaf** [comment] 2023-01-27 10:56
Thanks @johhnry for bringing this up and thanks @benfry for the clarification! Closing this as "acceptable white lie" ;)

**Closed by SableRaf** 2023-01-27 10:56 UTC
